# Generated by Django 3.0.7 on 2020-06-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessagemodel',
            name='message_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
