# Generated by Django 3.0.7 on 2020-06-19 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headlineapi', '0004_auto_20200617_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTelegramUserJoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineapi.TelegramBotModel')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineapi.TelegramUserModel')),
            ],
            options={
                'unique_together': {('bot_user', 'bot')},
            },
        ),
    ]
